#! /bin/sh
# Wrap Zile for help2man
# Add two spaces before options so they will be processed properly.

if test "$1" = "--help"; then
  src/xzile $1 | sed 's/^\([-+F]\)/  \1/'
else
  src/xzile $1
fi
